---
title: "Help - Helsinki city bike availability"
output: 
  md_document
---
# Help

### Selection

You can select the desired day of the week, time and optionally one or multiple stations. If there are no stations selected, the application will show all the stations. The 15-minute time interval is available from 5:00 to 22:00 so night-time is not included. After selection the markers for the chosen stations appear on the map. Markers are color-coded by the ratio of predicted amount of available bikes at the chosen time and the size of the station.


### Marker colors

The meaning of different colors are as followed:

  - Grey: less than 25 percent of the station's bikes are available 
  - Red: 25 - 49 percent of the station's bikes are available
  - Orange: 50 - 74 percent of the station's bikes are available
  - Green: 75 - 100 percent of the station's bikes are available

### Prediction

If you click the marker on the map, you can see the amount of available bikes that was predicted.

The predicted values are approximations based on statistical modelling and the accuracy of the prediction may vary between stations.  


### Authors

**Data processing and wrangling:** Veera Nenonen  
**Data analysis and modeling:** Patrik Lauha  
**Application development:** Joni Oksanen

